lore-id-text: '&6Starter Item'

starter-items:
  ironhelmet:
    Material: IRON_HELMET
    ArmorContent: HELMET
    DisplayName: '&a&lStarter Helmet'
    DisplayLore:
      - '&7Pretty good helmet!'
      - '&7Beat it!'
  ironchestplate:
    Material: IRON_CHESTPLATE
    ArmorContent: CHESTPLATE
    DisplayName: '&a&lStarter Chestplate'
    DisplayLore:
      - '&7The strongest part of armor!'
      - '&7Beat it!'
    Enchantments:
      DURABILITY: 1
      PROTECTION_ENVIRONMENTAL: 1
  ironleggings:
    Material: IRON_LEGGINGS
    ArmorContent: LEGGINGS
    DisplayName: '&a&lStarter Leggings'
    DisplayLore:
      - '&7Not the strongest, but...'
      - '&7Beat it!'
  ironboots:
    Material: IRON_BOOTS
    ArmorContent: BOOTS
    DisplayName: '&a&lStarter Boots'
    DisplayLore:
      - '&7You have feet!'
  sword:
    Material: IRON_SWORD
    DisplayName: '&a&lStarter Sword'
  bread:
    Material: BREAD
    Amount: 16
    DisplayName: '&a&lStarter Bread'
    DisplayLore:
      - "&7It's just the bread"